spring:
  cloud:
    config:
      server:
        git:
         uri: https://github.com/aniljha91/microservices-Arch
         search-paths:
           - '/config-server/src/main/resources/shared'
         username: aniljha91
         password: Github_9791
          #uri: https://github.com/aniljha91/microservices-Arch/tree/master/config-server
          #searchPaths: ConfigData
        #native:
          #search-locations: classpath:/shared
  #profiles:
     #active: native

eureka:
  client:
    serviceUrl:
      defaultZone: http://ec2-34-212-49-187.us-west-2.compute.amazonaws.com:8762/eureka/
      #defaultZone: http://localhost:8762/eureka/
  instance:
    prefer-ip-address: true
    
server:
  port: 8889

security:
  user: 
    password: password
